service: backend
runtime: nodejs18
env: standard

env_variables:
  GOOGLE_API_KEY: "AIzaSyCXW5z1VlxxIPn3yuNBWN3jF2PqokEE5O8"
  TOMORROW_API_KEY: "A5DJcnpePhbi8XZVx2heW8B0xsI6J3Cx"
  MONGO_URI: "mongodb+srv://gliucs571:LN67If6N8W58P3qp@cluster0.bblat.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5

entrypoint: node server.js
